// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demosite.Models;

namespace demosite.Migrations
{
    [DbContext(typeof(demositeContext))]
    [Migration("20181119203307_sec")]
    partial class sec
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("demosite.Models.Facility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Buildings");

                    b.Property<string>("Floors");

                    b.Property<string>("People")
                        .IsRequired();

                    b.Property<string>("Rooms");

                    b.HasKey("ID");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("demosite.Models.PersonsBuilding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FacilityID");

                    b.Property<int>("Person_id");

                    b.Property<int>("pb_id");

                    b.HasKey("ID");

                    b.HasIndex("FacilityID");

                    b.ToTable("PersonsBuilding");
                });

            modelBuilder.Entity("demosite.Models.PersonsBuilding", b =>
                {
                    b.HasOne("demosite.Models.Facility")
                        .WithMany("PersonsBuildings")
                        .HasForeignKey("FacilityID");
                });
#pragma warning restore 612, 618
        }
    }
}
